### ISSUE TITLE
Stop executing evaluation

### ISSUE THREAD

**Issue by Rocche** [richorama/IronBlock#15]
Hi man,
first of all: thank you for this awesome library!
Now, considering that I will run long tasks with blocks (minimum half a minute), I'd like to implement a mechanism to cancel the current execution. How can I do?

**Comment by richorama** [comment]
Hi @Rocche, thanks!

It's great to hear that people are finding the code useful.

To answer your question, there isn't a feature in IronBlock to cancel execution. I suggest for the meantime that you start the execution in a separate thread, which you can then cancel, i.e. 
 https://stackoverflow.com/a/1865617/349014

If you're building your own blocks, you could conceivably pass a cancellation token in as an input.

Ultimately it would be nice to have this as a first class feature, although there is no direct expression for this in blockly, you could use Task<T> as outputs, and support cancellation properly.

**Comment by Rocche** [comment]
Hi @richorama ,
thanks for the reply! I solved my issue adding the cancellation token as attribute of the Context class, so I can use it directly in Evaluate functions of my blocks.
Your reply was really helpful, thank you for support and keep doing awesome code!

**Comment by richorama** [comment]
👍
