### ISSUE TITLE
Index of return result can not be evaluated against a MathNumber

### ISSUE THREAD

**Issue by dprice809** [richorama/IronBlock#17]
When comparing the index returned by the IndexOf block to a MathNumber an exception is thrown "Unable to cast object of type System.Int32 to type System.Double". This is because the MathNumber block returns a Double while the IndexOf block returns an Int32. 

[Blockly Screenshot](https://i.imgur.com/iHPk5hn.png)

**Comment by richorama** [comment]
Excellent find! I'll change the `IndexOf` block to return a double.

Out of curiosity, are you just playing with IronBlock, or are you a serious user?

**Comment by richorama** [comment]
Fixed by version 1.0.4

**Comment by dprice809** [comment]
> Excellent find! I'll change the `IndexOf` block to return a double.
> 
> Out of curiosity, are you just playing with IronBlock, or are you a serious user?

I am currently prototyping something for work. I expect to be writing custom blocks. So I may break some other things along the way. I'll try contribute as I start to become more familiar with writing custom pieces.

**Comment by richorama** [comment]
great to hear, contributions are very welcome!
