### ISSUE TITLE
Help with WebAPI to Blockly

### ISSUE THREAD

**Issue by ignatandrei** [richorama/IronBlock#28]
Hello ,
I have created another component with Blockly: 

It takes WebAPI ( + swagger + OData ) specification and transforms to Blockly blocks with Javascript. For an example, see https://netcoreblockly.herokuapp.com/blockly.html .

I think that your project can be usefull to execute also on the backend , not just to the frontend.

For this, I need some help about how to implement

TypeArgumentBase  -  this is the value
ActionInfo - this is the function ( WebAPI , ODATA, and so on)

( To understand ,you could start from

```
  var strDef = GenerateDefinitionString(type);
            var strJS = GenerateJSstring(type);


```
it will be helpfull if it will have a GenerateC#  or similar

Waiting for your answer

**Comment by richorama** [comment]
Hi. Thanks for your interest in this project!

I’m away from my computer for a few days having just moved house. I’ll take a look next week. 

Iron block does already allow you to translate blockly to c#, however it may not be perfect. 

Thanks,

Richard.

**Comment by richorama** [comment]
Hi, I took a look at your link, but I got an error :¬(

Let me know how I can help you, as it sounds like you've got an interesting idea.

**Comment by ignatandrei** [comment]
It works now. Please try agsin

**Comment by ignatandrei** [comment]
@richorama   : Did you have the time to look ?

**Comment by ignatandrei** [comment]
Latest call ;-)

**Comment by richorama** [comment]
Thanks for the reminder :¬)

Your project looks cool. I'm very happy to help you, but I don't really know how. You have two lines of code in your comment, but I'm not sure how IronBlock fits into this.

**Comment by ignatandrei** [comment]
Very easy.
Please see 
 https://netcoreblockly.herokuapp.com/

Press " execute " 
It executes WeatherForecast 4 times from javascript, calling the backend

The project is https://github.com/ignatandrei/NETCoreBlockly . The VS2019 sln is  src/NetCore2Blockly/NetCore2Blockly.sln . The project is Test/TestBlocklyHtml

Could you explain , please , how can I execute this on the backend with your IronBlock ( or make a PR with this )  ?

( Even if you do not call WeatherForecast  , it will help if you show on my project how to execute the some blocks on the backend with your IronBlock )

( You will be between contributors , at least ;-) )

Thanks for your time,
Andrei

**Comment by richorama** [comment]
great, I'll see what I can do :¬)

**Comment by richorama** [comment]
I remembered that I have a demo that does something quite similar to what you're possibly thinking (it even uses the current weather as an example!)

Have a look at this repo: https://github.com/richorama/IronDemo

It allows you to design a blockly program that runs in .netcore, calling out to a 3rd party API.

![Screenshot from 2020-07-09 12-09-31](https://user-images.githubusercontent.com/353138/87032892-3509f680-c1dd-11ea-934c-72b03820ddcc.png)

**Comment by ignatandrei** [comment]
Great. I will take a look today! Thanks for the tip!

**Comment by ignatandrei** [comment]
I see now . Pretty easy - if I generate call for each blocks. Thank you. I will keep you posted!

**Comment by ignatandrei** [comment]
Just another question about the static
CustomPrintBlock.Text.Clear();
...
return this.Content(string.Join('\n',CustomPrintBlock.Text));

It is not thread safe. ( What if 2 users running almost simultaneously the Execute ?)

Could you make thread safe ?

**Comment by richorama** [comment]
yes, it's a nasty hack. I'll have a think about making it thread safe ;¬)

**Comment by richorama** [comment]
Done with this PR: https://github.com/richorama/IronDemo/pull/1

**Comment by ignatandrei** [comment]
Thanks! Now, all I should do is to integrate with my project!
