### ISSUE TITLE
New Features (execution interrupt, Before After hooks)

### ISSUE THREAD

**Issue by maciejmatuszak** [richorama/IronBlock#35]
Hi Richard,
I am planning to use the IronBlocks in my app, I need to add some features:
- Separate thread executor
- improve hierarchical context (hierarchical variable evaluation)
- interrupt/resume/step execution (at block granularity)
- fixed rate execution (blocks/per minute - mainly for visualisation)
- execution logging/visualisation (Before/After block hooks - mainly to highlight the current block in Blockly)

Would you be interesting in collaboration/pulling the changes in?

**Comment by richorama** [comment]
Yes. These sound like some excellent suggestions. I’m really pleased that you’re thinking of picking ironblock for your project, and I’d be happy to help. 

Ideally it would be good to split these into separate PRs if possible. 

Richard.

**Comment by maciejmatuszak** [comment]
Sound good,
will partition the changes and create separate issues.
Thanks Maciej
