### ISSUE TITLE
Infinite nested NEXT on finite sequence

### ISSUE THREAD

**Issue by justinvvitale** [richorama/IronBlock#39]
Hi, I am having an issue with the following XML:

![image](https://user-images.githubusercontent.com/4002351/103607511-32f6d980-4f6d-11eb-915c-a41c75c1b8d5.png)

https://gist.github.com/justinvvitale/1e2e476b4d5624b306ab0b1cd4f361d6

It appears in Blockly as such:
![image](https://user-images.githubusercontent.com/4002351/103607141-59684500-4f6c-11eb-9e5c-2775d967531b.png)

However the parser interprets it as the following:

![image](https://user-images.githubusercontent.com/4002351/103607293-a3512b00-4f6c-11eb-98ae-20d4575f31d3.png)

It appears to loop indefinitely.

Am I missing something or is this a bug.

An unrelated question I have is why do my waitblocks share the same fields but have a different ID ( shouldn't they be a new object?). I think I am doing something wrong, a way around this would be to clear the fields after consuming them but this doesn't seem right.

![image](https://user-images.githubusercontent.com/4002351/103607401-edd2a780-4f6c-11eb-928d-c37029416841.png)

Thanks

**Comment by justinvvitale** [comment]
Did a little bit of snooping around, I believe it's sharing the same memory address, when it sets the first wait's next, it sets it for both and just causes an infinite loop. Why doesn't each block have unique memory allocated to it if they have a different Id?

**Comment by justinvvitale** [comment]
Fixed by using

parser.AddBlock<WaitBlock>("wait");

**instead of** 

parser.AddBlock("wait", new Waitblock);

Wasn't as simple as that since I was reflection but it was because it was reusing the same object and causes problems when you have multiple.

This also resolves my field problem (They now have unique fields since they're constructed dynamically)

**Comment by richorama** [comment]
I'm glad you found the solution. You can also do this (if I remember correctly)

```cs
parse.AddBlock("wait", () => new Waitblock());
```
