### ISSUE TITLE
Remove C# codegen

### ISSUE THREAD

**Issue by richorama** [richorama/IronBlock#43]
Does anyone use the codegen? I was thinking of bumping to 2.0.0 and removing it.

**Comment by gekah** [comment]
Planned on using it, but can probably also go the interpreted route. Care to share the rationale behind (considering) dropping it - getting rid of dependencies / code ballast / maintenance overhead / complexity of SyntaxFactory?

**Comment by richorama** [comment]
The maintainability of it is my primary concern. I'm not sure if it works 100%, or if it's useful.

**Comment by benni1972** [comment]
Hi 
we make heavy use of the c# code generation, as we use it as an assistant tool to generate application specific c# in combination with standard c# code which will be stored in a database and executed later.
We therefore have lot of CustomBlocks and corresponding IBlock-Classes for them that only implement the Generate() method.
We do not work with Evaluate() at all.
So the cutting of c# code generation would be a big loss for us.

**Comment by richorama** [comment]
understood, thank you for the feedback, and thank you for using IronBlock :¬)
