### ISSUE TITLE
Comments for code generation

### ISSUE THREAD

**Issue by benni1972** [richorama/IronBlock#48]
Is there a chance that you can include the blockly comments as "real" comments in code generation (for evaluation this is not needed).

Currently I'm using a custom comment block containing a text input field. During code creation I then create an empty statement with a comment trivia containing the text from the input field  which is then set as trailing trivia  on the empty statement.

This works, but the generated code looks a bit unconventional with every comment starting with a semicolon.

Btw.: Thanks for keeping the code generation alive ;)

**Comment by richorama** [comment]
Hi, Yes I'm sure we can do this. Happy to take a PR, or something I can
look at later.

:¬)

**Comment by benni1972** [comment]
Sorry, but I'm not so deepin this code that I could provide a PR.

**Comment by richorama** [comment]
closed by #49
