### ISSUE TITLE
Problem with getting field value from custom block

### ISSUE THREAD

**Issue by Amboryus** [richorama/IronBlock#52]
I have folowing XML:
```xml
<xml xmlns="https://developers.google.com/blockly/xml">
  <block type="math_arithmetic" id="|A4ulz@A}mGUo0h3pZR|" x="244" y="356">
    <field name="OP">ADD</field>
    <value name="A">
      <block type="ParamBlock" id="aFD-Tf.=);AUrQC^qIOy">
        <field name="PARAM_INDEX">0</field>
        <value name="LIST">
          <block type="ParamListBlock" id="4:q.0!x,?(K!S7@b|{+h">
            <field name="DEBUG_VALUE">0</field>
          </block>
        </value>
      </block>
    </value>
    <value name="B">
      <block type="ParamBlock" id="tZ%.6rM?c^ig`Wa[~cdo">
        <field name="PARAM_INDEX">1</field>
        <value name="LIST">
          <block type="ParamListBlock" id="NmsQHLb{Mb=?6duWrbR;">
            <field name="DEBUG_VALUE">0</field>
          </block>
        </value>
      </block>
    </value>
  </block>
</xml>
```

Here is the Custom block:
```csharp
public class ParamBlock: IBlock
  {
    public override object Evaluate(Context context)
    {
      // read a field
      var index= this.Fields.Get("PARAM_INDEX");

      // evaluate a value
      var list= this.Values.Evaluate("LIST", context);

     return list[index];
    }
  }
```

I added my CustomBlock with
```csharp
var block = new ParamBlock();
parser.AddBlock("ParamBlock", block);
```
During debugging of the code the debugger run for two times in the method "Evaluate". So for so good.
- The property "Id" is always "tZ%.6rM?c^ig`Wa[~cdo".
- The Property "Fields" contains always the fields of both blocks.
- The property "Values" contains always the values of both blocks.

In my opinion it has to be:
- each block instance has his own id.
- each block contains only the field and values for himself.

I am a little bit confused. ;-)

**Comment by richorama** [comment]
Hi @Amboryus thanks for trying out IronBlock!

There are different ways to add blocks to the parser, the method you have selected is suitable for adding a singleton block instance, which is useful in some cases (such as writing to stdout). 


```cs
    public Parser AddBlock<T>(string type) where T : IBlock, new()
    {
      this.AddBlock(type, () => new T());
      return this;
    }

    public Parser AddBlock<T>(string type, T block) where T : IBlock
    {
      this.AddBlock(type, () => block);
      return this;
    }

    public Parser AddBlock(string type, Func<IBlock> blockFactory)
    {
      if (this.blocks.ContainsKey(type))
      {
        this.blocks[type] = blockFactory;
        return this;
      }
      this.blocks.Add(type, blockFactory);
      return this;
    }
```

In your case you might find that either of the other overloads are more appropriate, where you either just define the type of the block, and the instance is activated for you, or you provide a factory method.

I hope this helps?

Please reach out if you have any more questions.

**Comment by Amboryus** [comment]
Yes, that's it!
That's logical! When i inject a living single instance of a block type, than that is the result.

My fault.

It's working now.

Thank you so much!
