### ISSUE TITLE
Typo/CopyPasteError in LogicTernary.cs

### ISSUE THREAD

**Issue by JMS-1** [richorama/IronBlock#60]
If someone is still interested: I think https://github.com/richorama/IronBlock/blob/master/IronBlock/Blocks/Logic/LogicTernary.cs#L27 should call Evaluate not Generate.

Regards

Jochen

**Comment by danijerez** [comment]
I'm interested but I think the project is a bit abandoned, I've seen that a fork has started, do you plan to continue it?

**Comment by JMS-1** [comment]
Currently hard to say but definity not as is. If - and this is a big if - it goes on more server centric e.g. multithreading, error handling, ...

**Comment by richorama** [comment]
Hi All, Sorry, I don't get a lot of time to maintain this project. I wouldn't say it was dead, but I'm happy to carve out some time to work on it if it's valuable to people.
PRs are welcome.

**Comment by richorama** [comment]
fixed in version 1.0.18
